config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  get "up" => "rails/health#show", as: :rails_health_check

  resources :patients do
    collection do
      get 'patient_stats'
    end
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :dob, presence: true
  end
  

app/models/user.rb
class User < ApplicationRecord
  enum role: { receptionist: 0, doctor: 1 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  protect_from_forgery with: :exception

  before_action :set_layout

  private

  def set_layout
    # Set the layout to 'navigate' only if the user is logged in
    if current_user
      self.class.layout 'navigate'
    else
      # Use the default application layout if the user is not logged in
      self.class.layout 'application'
    end
  end

  def after_sign_in_path_for(resource)
    # Redirect to the patients index view after login
    patients_path
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_patient, only: [:show, :edit, :update, :destroy]
  
    def index
      @patients = policy_scope(Patient)
      authorize @patients
    end
  
    def show
      authorize @patient
    end
  
    def new
      @patient = Patient.new
      authorize @patient
    end
  
    def edit
      authorize @patient
    end
  
    def create
      @patient = Patient.new(patient_params)
      authorize @patient
  
      if @patient.save
        redirect_to @patient, notice: 'Patient was successfully created.'
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def update
      authorize @patient
      if @patient.update(patient_params)
        redirect_to @patient, notice: 'Patient was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      authorize @patient
      @patient.destroy
      redirect_to patients_url, notice: 'Patient was successfully destroyed.'
    end
  
    def patient_stats
      authorize :patient, :patient_stats?
      patient_creations_by_day = Patient.group("DATE(created_at)").count
      @patient_creations_data = patient_creations_by_day.map { |date, count| [date.to_s, count] }
    end

    private
  
    def set_patient
      @patient = Patient.find(params[:id])
    end
  
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :dob, :gender)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portal Login</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/navigate.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portal</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <main class="flex">
    <% if current_user %>
      <nav class="w-64 p-4 h-screen bg-gray-600 sticky top-0">
        <div class="flex">
          <h1 class="text-md py-2 text-white font-bold hidden md:block"><%= (current_user.role).capitalize %></h1>
        </div>
        <ul class="flex flex-col text-white">
          <li>
            <%= link_to patients_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
              <%= icon('fa-solid', 'user', class: 'mr-2') %> <span class="hidden md:inline-block">Patients</span>
            <% end %>
          </li>
          <% if policy(Patient.new).create? %>
            <li>
              <%= link_to new_patient_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'add', class: 'mr-2') %> <span class="hidden md:inline-block">New Patient</span>
              <% end %>
            </li>
          <% end %>
          <% if policy(Patient).patient_stats? %>
            <li>
              <%= link_to patient_stats_patients_path, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
                <%= icon('fa-solid', 'bar-chart', class: 'mr-2') %> <span class="hidden md:inline-block">Patient Stats</span>
              <% end %>
            </li>
          <% end %>
          <li>
          <%= link_to destroy_user_session_path, data: { "turbo-method": :delete, "turbo-confirm": "Are you sure?" }, class: "block px-4 py-2 hover:rounded hover:bg-gray-700" do %>
            <%= icon('fa-solid', 'sign-out', class: 'mr-2') %> <span class="hidden md:inline-block">Sign Out</span>
          <% end %>
        </li>
        </ul>
      </nav>    
      <div class="flex-1">
        <%= yield %>
      </div>
    <% end %>
  </main>
</body>
</html>

app/views/patients/_form.html.erb
<!-- app/views/patients/_form.html.erb -->
<%= form_with(model: @patient, local: true) do |form| %>


  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :dob %>
    <%= form.date_field :dob, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :gender %>
    <%= form.select :gender, [['Male', 'male'], ['Female', 'female'], ['Other', 'other']], {}, class: 'form-select' %>
  </div>

  <div class="inline">
    <%= form.submit class: "custom-link" %>
<% end %>

app/views/patients/edit.html.erb
<!-- app/views/patients/edit.html.erb -->
<header class="text-center p-4 bg-gray-100">
<h1 class="font-bold text-4xl">Edit Patient</h1>
</header>

<%= render 'form', patient: @patient %>

<%= link_to 'Cancel', patient_path(@patient), class: "custom-link" %>

app/views/patients/index.html.erb
<div class="w-full">

  <header class="text-center p-4 bg-gray-100">
    <h1 class="font-bold text-4xl">Patients</h1>
  </header>

  <div class="flex flex-col items-center">
    <div class="overflow-x-auto w-full">
      <table class="min-w-full">
        <thead class="bg-white border-b">
          <tr>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
              ID
            </th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
              First Name
            </th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
              Last Name
            </th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
              Date of Birth
            </th>
            <th scope="col" class="text-sm font-medium text-gray-800 px-6 py-4 text-left">
              Gender
            </th>
          </tr>
        </thead>
        <tbody>
          <% @patients.each do |patient| %>
            <tr class="bg-gray-50 border-b">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800 underline">
                <% if policy(patient).update? %>
                  <%= link_to patient.id, patient_path(patient) %>
                <% else %>
                  <%= patient.id %>
                <% end %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                <%= patient.first_name %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                <%= patient.last_name %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                <%= patient.dob %>
              </td>
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-800">
                <%= patient.gender %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<header class="text-center p-4 bg-gray-100">
  <h1 class="font-bold text-4xl">New Patient</h1>
</header>

<%= form_for(@patient) do |f| %>
    <% if @patient.errors.any? %>
    <div id="error_explanation" class="text-red-500 font-bold">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>
      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form', f: f %>

  <%= link_to 'Cancel', patients_path, class: "custom-link" %>
<% end %>

app/views/patients/patient_stats.html.erb
<div class="my-8 w-full">
  <header class="text-center p-4 bg-gray-100">
  <h1 class="font-bold text-4xl">Patient Stats</h1>
  </header>
  <div class="w-full" data-controller="dashboard" data-dashboard-patient-creations-value="<%= @patient_creations_data.to_json %>">
    <canvas id="patientCreationsChart"></canvas>
  </div>
</div>

app/views/patients/show.html.erb
<!-- app/views/patients/show.html.erb -->

<div class="w-full">

  <header class="text-center p-4 bg-gray-100">
    <h1 class="font-bold text-4xl">Patient Details</h1>
  </header>

  <div class="mx-4 my-8"> 
    <div class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer mb-4">
      <%= link_to "Edit Patient", edit_patient_path(@patient) %>
    </div>
    
    <% if policy(Patient.new).destroy? %>
      <div class="rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer mb-4">
      <%= link_to "Delete", patient_path(@patient), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      </div>
    <% end %>

    <div class="bg-white shadow overflow-hidden sm:rounded-lg">
      <div class="px-4 py-5 sm:px-6">
        <h3 class="text-lg font-medium leading-6 text-gray-900">Patient: <%= (@patient.first_name).capitalize + " " + (@patient.last_name).capitalize %></h3>
        <p class="mt-1 max-w-2xl text-sm text-gray-500">Details about the patient.</p>
      </div>
      <div class="border-t border-gray-200">
        <dl>
          <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">ID</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2"><%= @patient.id %></dd>
          </div>
          <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">First Name</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2"><%= @patient.first_name %></dd>
          </div>
          <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">Last Name</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2"><%= @patient.last_name %></dd>
          </div>
          <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">Date of Birth</dt>
            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2"><%= @patient.dob %></dd>
          </div>
        </dl>
      </div>
    </div>
  </div>
</div>